name: Modify Existing Activity
description: Request changes to an existing extracurricular activity
title: "[Modify Activity]: "
labels: ["enhancement", "activity"]
body:
  - type: markdown
    attributes:
      value: |
        ## Modify an Existing Activity
        Use this form to request changes to an existing extracurricular activity.
        Only fill in the fields you want to change - leave others blank.

  - type: input
    id: activity-name
    attributes:
      label: Activity Name
      description: Which activity do you want to modify?
      placeholder: e.g., Chess Club, Soccer Team, Art Club
    validations:
      required: true

  - type: dropdown
    id: change-type
    attributes:
      label: What do you want to change?
      description: Select the type of change you need
      options:
        - Change schedule (days/times)
        - Change description
        - Change maximum participants
        - Change category
        - Multiple changes
        - Other
    validations:
      required: true

  - type: textarea
    id: new-description
    attributes:
      label: New Description (if changing)
      description: Provide the new description for the activity
      placeholder: Leave blank if not changing the description

  - type: dropdown
    id: new-category
    attributes:
      label: New Category (if changing)
      description: Select the new category for this activity
      options:
        - Not changing
        - Sports
        - Arts
        - Academic
        - Community
        - Technology

  - type: checkboxes
    id: new-schedule-days
    attributes:
      label: New Days of the Week (if changing)
      description: Select all days when this activity will meet (leave unchecked if not changing)
      options:
        - label: Monday
        - label: Tuesday
        - label: Wednesday
        - label: Thursday
        - label: Friday
        - label: Saturday
        - label: Sunday

  - type: input
    id: new-start-time
    attributes:
      label: New Start Time (if changing)
      description: When should the activity start? (Use 24-hour format like 15:30 for 3:30 PM)
      placeholder: e.g., 15:30 for 3:30 PM, leave blank if not changing

  - type: input
    id: new-end-time
    attributes:
      label: New End Time (if changing)
      description: When should the activity end? (Use 24-hour format like 17:00 for 5:00 PM)
      placeholder: e.g., 17:00 for 5:00 PM, leave blank if not changing

  - type: input
    id: new-max-participants
    attributes:
      label: New Maximum Participants (if changing)
      description: What should the new maximum number of students be?
      placeholder: e.g., 25, leave blank if not changing

  - type: textarea
    id: reason
    attributes:
      label: Reason for Change
      description: Why is this change needed?
      placeholder: Explain why these modifications are necessary
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Any other details we should know?
      placeholder: Add any extra information here

  - type: markdown
    attributes:
      value: |
        ---
        ### Acceptance Criteria
        - The activity details should be updated as requested
        - Changes should be reflected immediately on the website
        - Existing student registrations should remain intact
        - The activity should remain filterable by its updated properties

        ### Technical Notes for Implementation
        - Locate the activity in the `initial_activities` dictionary in `src/backend/database.py`
        - Update only the specified fields while preserving all other data
        - Ensure the schedule format is consistent with existing activities
        - If changing schedule, update both the human-readable and structured formats
        - Verify that the changes don't break any existing functionality
